version: 2.0.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: Any CPU
clone_folder: C:\TheCrafters001\Build\Game-Updater
before_build:
- ps: nuget restore 'C:\TheCrafters001\Build\Game-Updater\src\Game Updater.sln'
build:
  verbosity: minimal